// Code generated by protoc-gen-gogo.
// source: github.com/fuserobotics/rethinkts/proto/metric.proto
// DO NOT EDIT!

/*
	Package metric is a generated protocol buffer package.

	It is generated from these files:
		github.com/fuserobotics/rethinkts/proto/metric.proto

	It has these top-level messages:
		MetricIdentifier
		MetricSeries
		MetricDatapoint
		MetricDatapointWithMeta
*/
package metric

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import common "github.com/fuserobotics/proto/common"

import errors "errors"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

type MetricSeries_MetricDataType int32

const (
	MetricSeries_NUMBER MetricSeries_MetricDataType = 0
)

var MetricSeries_MetricDataType_name = map[int32]string{
	0: "NUMBER",
}
var MetricSeries_MetricDataType_value = map[string]int32{
	"NUMBER": 0,
}

func (x MetricSeries_MetricDataType) String() string {
	return proto.EnumName(MetricSeries_MetricDataType_name, int32(x))
}
func (MetricSeries_MetricDataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorMetric, []int{1, 0}
}

type MetricSeries_MetricTagIndexType int32

const (
	MetricSeries_NONE     MetricSeries_MetricTagIndexType = 0
	MetricSeries_STANDARD MetricSeries_MetricTagIndexType = 1
	MetricSeries_GEOPOINT MetricSeries_MetricTagIndexType = 2
)

var MetricSeries_MetricTagIndexType_name = map[int32]string{
	0: "NONE",
	1: "STANDARD",
	2: "GEOPOINT",
}
var MetricSeries_MetricTagIndexType_value = map[string]int32{
	"NONE":     0,
	"STANDARD": 1,
	"GEOPOINT": 2,
}

func (x MetricSeries_MetricTagIndexType) String() string {
	return proto.EnumName(MetricSeries_MetricTagIndexType_name, int32(x))
}
func (MetricSeries_MetricTagIndexType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorMetric, []int{1, 1}
}

// Used to identify a stored metric
type MetricIdentifier struct {
	// Use a string identifier for now.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MetricIdentifier) Reset()                    { *m = MetricIdentifier{} }
func (m *MetricIdentifier) String() string            { return proto.CompactTextString(m) }
func (*MetricIdentifier) ProtoMessage()               {}
func (*MetricIdentifier) Descriptor() ([]byte, []int) { return fileDescriptorMetric, []int{0} }

type MetricSeries struct {
	Id             string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                                        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                                        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DataType       MetricSeries_MetricDataType                   `protobuf:"varint,5,opt,name=data_type,json=dataType,proto3,enum=metric.MetricSeries_MetricDataType" json:"data_type,omitempty"`
	TagDescription map[string]*MetricSeries_MetricTagDescription `protobuf:"bytes,6,rep,name=tag_description,json=tagDescription" json:"tag_description,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MetricSeries) Reset()                    { *m = MetricSeries{} }
func (m *MetricSeries) String() string            { return proto.CompactTextString(m) }
func (*MetricSeries) ProtoMessage()               {}
func (*MetricSeries) Descriptor() ([]byte, []int) { return fileDescriptorMetric, []int{1} }

func (m *MetricSeries) GetTagDescription() map[string]*MetricSeries_MetricTagDescription {
	if m != nil {
		return m.TagDescription
	}
	return nil
}

type MetricSeries_MetricTagDescription struct {
	Index       MetricSeries_MetricTagIndexType `protobuf:"varint,1,opt,name=index,proto3,enum=metric.MetricSeries_MetricTagIndexType" json:"index,omitempty"`
	Title       string                          `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MetricSeries_MetricTagDescription) Reset()         { *m = MetricSeries_MetricTagDescription{} }
func (m *MetricSeries_MetricTagDescription) String() string { return proto.CompactTextString(m) }
func (*MetricSeries_MetricTagDescription) ProtoMessage()    {}
func (*MetricSeries_MetricTagDescription) Descriptor() ([]byte, []int) {
	return fileDescriptorMetric, []int{1, 1}
}

type MetricDatapoint struct {
	Timestamp int64               `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location  *common.GeoLocation `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Tags      map[string]string   `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *MetricDatapoint) Reset()                    { *m = MetricDatapoint{} }
func (m *MetricDatapoint) String() string            { return proto.CompactTextString(m) }
func (*MetricDatapoint) ProtoMessage()               {}
func (*MetricDatapoint) Descriptor() ([]byte, []int) { return fileDescriptorMetric, []int{2} }

func (m *MetricDatapoint) GetLocation() *common.GeoLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *MetricDatapoint) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type MetricDatapointWithMeta struct {
	Datapoint *MetricDatapoint  `protobuf:"bytes,1,opt,name=datapoint" json:"datapoint,omitempty"`
	Metric    *MetricIdentifier `protobuf:"bytes,2,opt,name=metric" json:"metric,omitempty"`
}

func (m *MetricDatapointWithMeta) Reset()                    { *m = MetricDatapointWithMeta{} }
func (m *MetricDatapointWithMeta) String() string            { return proto.CompactTextString(m) }
func (*MetricDatapointWithMeta) ProtoMessage()               {}
func (*MetricDatapointWithMeta) Descriptor() ([]byte, []int) { return fileDescriptorMetric, []int{3} }

func (m *MetricDatapointWithMeta) GetDatapoint() *MetricDatapoint {
	if m != nil {
		return m.Datapoint
	}
	return nil
}

func (m *MetricDatapointWithMeta) GetMetric() *MetricIdentifier {
	if m != nil {
		return m.Metric
	}
	return nil
}

func init() {
	proto.RegisterType((*MetricIdentifier)(nil), "metric.MetricIdentifier")
	proto.RegisterType((*MetricSeries)(nil), "metric.MetricSeries")
	proto.RegisterType((*MetricSeries_MetricTagDescription)(nil), "metric.MetricSeries.MetricTagDescription")
	proto.RegisterType((*MetricDatapoint)(nil), "metric.MetricDatapoint")
	proto.RegisterType((*MetricDatapointWithMeta)(nil), "metric.MetricDatapointWithMeta")
	proto.RegisterEnum("metric.MetricSeries_MetricDataType", MetricSeries_MetricDataType_name, MetricSeries_MetricDataType_value)
	proto.RegisterEnum("metric.MetricSeries_MetricTagIndexType", MetricSeries_MetricTagIndexType_name, MetricSeries_MetricTagIndexType_value)
}
func (m *MetricIdentifier) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricIdentifier) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintMetric(data, i, uint64(len(m.Id)))
		i += copy(data[i:], m.Id)
	}
	return i, nil
}

func (m *MetricSeries) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricSeries) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintMetric(data, i, uint64(len(m.Id)))
		i += copy(data[i:], m.Id)
	}
	if len(m.Title) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintMetric(data, i, uint64(len(m.Title)))
		i += copy(data[i:], m.Title)
	}
	if len(m.Description) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintMetric(data, i, uint64(len(m.Description)))
		i += copy(data[i:], m.Description)
	}
	if m.DataType != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintMetric(data, i, uint64(m.DataType))
	}
	if len(m.TagDescription) > 0 {
		for k, _ := range m.TagDescription {
			data[i] = 0x32
			i++
			v := m.TagDescription[k]
			if v == nil {
				return 0, errors.New("proto: map has nil element")
			}
			msgSize := v.Size()
			mapSize := 1 + len(k) + sovMetric(uint64(len(k))) + 1 + msgSize + sovMetric(uint64(msgSize))
			i = encodeVarintMetric(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintMetric(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x12
			i++
			i = encodeVarintMetric(data, i, uint64(v.Size()))
			n1, err := v.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n1
		}
	}
	return i, nil
}

func (m *MetricSeries_MetricTagDescription) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricSeries_MetricTagDescription) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintMetric(data, i, uint64(m.Index))
	}
	if len(m.Title) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintMetric(data, i, uint64(len(m.Title)))
		i += copy(data[i:], m.Title)
	}
	if len(m.Description) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintMetric(data, i, uint64(len(m.Description)))
		i += copy(data[i:], m.Description)
	}
	return i, nil
}

func (m *MetricDatapoint) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricDatapoint) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		data[i] = 0x8
		i++
		i = encodeVarintMetric(data, i, uint64(m.Timestamp))
	}
	if m.Location != nil {
		data[i] = 0x12
		i++
		i = encodeVarintMetric(data, i, uint64(m.Location.Size()))
		n2, err := m.Location.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.Tags) > 0 {
		for k, _ := range m.Tags {
			data[i] = 0x1a
			i++
			v := m.Tags[k]
			mapSize := 1 + len(k) + sovMetric(uint64(len(k))) + 1 + len(v) + sovMetric(uint64(len(v)))
			i = encodeVarintMetric(data, i, uint64(mapSize))
			data[i] = 0xa
			i++
			i = encodeVarintMetric(data, i, uint64(len(k)))
			i += copy(data[i:], k)
			data[i] = 0x12
			i++
			i = encodeVarintMetric(data, i, uint64(len(v)))
			i += copy(data[i:], v)
		}
	}
	return i, nil
}

func (m *MetricDatapointWithMeta) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *MetricDatapointWithMeta) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Datapoint != nil {
		data[i] = 0xa
		i++
		i = encodeVarintMetric(data, i, uint64(m.Datapoint.Size()))
		n3, err := m.Datapoint.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.Metric != nil {
		data[i] = 0x12
		i++
		i = encodeVarintMetric(data, i, uint64(m.Metric.Size()))
		n4, err := m.Metric.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func encodeFixed64Metric(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Metric(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMetric(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *MetricIdentifier) Size() (n int) {
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMetric(uint64(l))
	}
	return n
}

func (m *MetricSeries) Size() (n int) {
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMetric(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovMetric(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovMetric(uint64(l))
	}
	if m.DataType != 0 {
		n += 1 + sovMetric(uint64(m.DataType))
	}
	if len(m.TagDescription) > 0 {
		for k, v := range m.TagDescription {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
			}
			mapEntrySize := 1 + len(k) + sovMetric(uint64(len(k))) + 1 + l + sovMetric(uint64(l))
			n += mapEntrySize + 1 + sovMetric(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *MetricSeries_MetricTagDescription) Size() (n int) {
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovMetric(uint64(m.Index))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovMetric(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovMetric(uint64(l))
	}
	return n
}

func (m *MetricDatapoint) Size() (n int) {
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovMetric(uint64(m.Timestamp))
	}
	if m.Location != nil {
		l = m.Location.Size()
		n += 1 + l + sovMetric(uint64(l))
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovMetric(uint64(len(k))) + 1 + len(v) + sovMetric(uint64(len(v)))
			n += mapEntrySize + 1 + sovMetric(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *MetricDatapointWithMeta) Size() (n int) {
	var l int
	_ = l
	if m.Datapoint != nil {
		l = m.Datapoint.Size()
		n += 1 + l + sovMetric(uint64(l))
	}
	if m.Metric != nil {
		l = m.Metric.Size()
		n += 1 + l + sovMetric(uint64(l))
	}
	return n
}

func sovMetric(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMetric(x uint64) (n int) {
	return sovMetric(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MetricIdentifier) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetric
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricIdentifier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricIdentifier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetric(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetric
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricSeries) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetric
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricSeries: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricSeries: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataType", wireType)
			}
			m.DataType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.DataType |= (MetricSeries_MetricDataType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TagDescription", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthMetric
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var mapmsglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				mapmsglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if mapmsglen < 0 {
				return ErrInvalidLengthMetric
			}
			postmsgIndex := iNdEx + mapmsglen
			if mapmsglen < 0 {
				return ErrInvalidLengthMetric
			}
			if postmsgIndex > l {
				return io.ErrUnexpectedEOF
			}
			mapvalue := &MetricSeries_MetricTagDescription{}
			if err := mapvalue.Unmarshal(data[iNdEx:postmsgIndex]); err != nil {
				return err
			}
			iNdEx = postmsgIndex
			if m.TagDescription == nil {
				m.TagDescription = make(map[string]*MetricSeries_MetricTagDescription)
			}
			m.TagDescription[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetric(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetric
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricSeries_MetricTagDescription) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetric
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricTagDescription: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricTagDescription: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Index |= (MetricSeries_MetricTagIndexType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetric(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetric
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricDatapoint) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetric
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricDatapoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricDatapoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Timestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Location == nil {
				m.Location = &common.GeoLocation{}
			}
			if err := m.Location.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var keykey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				keykey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapkey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapkey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapkey := int(stringLenmapkey)
			if intStringLenmapkey < 0 {
				return ErrInvalidLengthMetric
			}
			postStringIndexmapkey := iNdEx + intStringLenmapkey
			if postStringIndexmapkey > l {
				return io.ErrUnexpectedEOF
			}
			mapkey := string(data[iNdEx:postStringIndexmapkey])
			iNdEx = postStringIndexmapkey
			var valuekey uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				valuekey |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			var stringLenmapvalue uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLenmapvalue |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLenmapvalue := int(stringLenmapvalue)
			if intStringLenmapvalue < 0 {
				return ErrInvalidLengthMetric
			}
			postStringIndexmapvalue := iNdEx + intStringLenmapvalue
			if postStringIndexmapvalue > l {
				return io.ErrUnexpectedEOF
			}
			mapvalue := string(data[iNdEx:postStringIndexmapvalue])
			iNdEx = postStringIndexmapvalue
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetric(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetric
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricDatapointWithMeta) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetric
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricDatapointWithMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricDatapointWithMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Datapoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Datapoint == nil {
				m.Datapoint = &MetricDatapoint{}
			}
			if err := m.Datapoint.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metric", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetric
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metric == nil {
				m.Metric = &MetricIdentifier{}
			}
			if err := m.Metric.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetric(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetric
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetric(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetric
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetric
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMetric
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMetric
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMetric(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMetric = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetric   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorMetric = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xf3, 0xa7, 0x64, 0x12, 0xa5, 0xd6, 0x36, 0x52, 0xa3, 0xa8, 0x42, 0xc1, 0x1c, 0x08,
	0x07, 0x12, 0x08, 0x20, 0x50, 0x25, 0x04, 0xad, 0x12, 0x55, 0x91, 0x68, 0x02, 0xdb, 0x20, 0x8e,
	0x95, 0x63, 0x6f, 0xdc, 0x55, 0x63, 0xaf, 0x65, 0x6f, 0x10, 0xb9, 0x72, 0xe7, 0xa9, 0xb8, 0x70,
	0xec, 0x23, 0x20, 0x9e, 0x84, 0xf5, 0xee, 0x2a, 0xb6, 0x4b, 0xda, 0x03, 0x07, 0xcb, 0x33, 0xdf,
	0x7e, 0xf3, 0x3f, 0x03, 0x2f, 0x3d, 0xca, 0xaf, 0xd6, 0x8b, 0xbe, 0xc3, 0xfc, 0xc1, 0x72, 0x1d,
	0x93, 0x88, 0x2d, 0x18, 0xa7, 0x4e, 0x3c, 0x88, 0x08, 0xbf, 0xa2, 0xc1, 0x35, 0x8f, 0x07, 0x61,
	0xc4, 0x38, 0x1b, 0xf8, 0x84, 0x47, 0xd4, 0xe9, 0x4b, 0x05, 0x55, 0x94, 0xd6, 0x79, 0x9a, 0xb1,
	0xf6, 0x98, 0xc7, 0x14, 0x77, 0xb1, 0x5e, 0x4a, 0x4d, 0x19, 0x26, 0x92, 0x32, 0xeb, 0x3c, 0xbf,
	0x2b, 0x98, 0x62, 0x0a, 0xd8, 0x67, 0x81, 0xfe, 0x29, 0x13, 0xcb, 0x02, 0xf3, 0x5c, 0xc6, 0x9a,
	0xb8, 0x24, 0xe0, 0x74, 0x49, 0x49, 0x84, 0x9a, 0x50, 0xa0, 0x6e, 0xdb, 0xe8, 0x1a, 0xbd, 0x1a,
	0x16, 0x92, 0xf5, 0xb3, 0x04, 0x0d, 0x45, 0xba, 0x20, 0x11, 0x25, 0xf1, 0x6d, 0x02, 0x6a, 0x41,
	0x99, 0x53, 0xbe, 0x22, 0xed, 0x82, 0x84, 0x94, 0x82, 0xba, 0x50, 0x77, 0x49, 0xec, 0x44, 0x34,
	0xe4, 0x94, 0x05, 0xed, 0xa2, 0x7c, 0xcb, 0x42, 0xe8, 0x3d, 0xd4, 0x5c, 0x9b, 0xdb, 0x97, 0x7c,
	0x13, 0x92, 0x76, 0x59, 0xbc, 0x37, 0x87, 0x8f, 0xfa, 0xba, 0x11, 0xd9, 0x80, 0x5a, 0x19, 0x09,
	0xee, 0x5c, 0x50, 0x71, 0xd5, 0xd5, 0x12, 0xfa, 0x04, 0xfb, 0xdc, 0xf6, 0x2e, 0xb3, 0x71, 0x2a,
	0xdd, 0x62, 0xaf, 0x3e, 0xec, 0xed, 0xf4, 0x33, 0xb7, 0xbd, 0x51, 0x4a, 0x1d, 0x07, 0x3c, 0xda,
	0xe0, 0x26, 0xcf, 0x81, 0x9d, 0x15, 0x1c, 0xec, 0xa0, 0x21, 0x13, 0x8a, 0xd7, 0x64, 0xa3, 0x8b,
	0x4e, 0x44, 0xf4, 0x0e, 0xca, 0x5f, 0xed, 0xd5, 0x5a, 0x55, 0x5d, 0x1f, 0x3e, 0xb9, 0x27, 0xf3,
	0xbc, 0x43, 0xac, 0xec, 0x8e, 0x0b, 0x6f, 0x8c, 0xce, 0x0f, 0x03, 0x5a, 0xbb, 0x38, 0xe8, 0x2d,
	0x94, 0x69, 0xe0, 0x92, 0x6f, 0x32, 0x62, 0x73, 0xf8, 0xf8, 0x7e, 0xef, 0x93, 0x84, 0x2a, 0x7b,
	0xa3, 0xac, 0xfe, 0x77, 0x24, 0xd6, 0x11, 0x34, 0xf3, 0xcd, 0x46, 0x00, 0x95, 0xe9, 0xe7, 0xf3,
	0xd3, 0x31, 0x36, 0xf7, 0xac, 0x63, 0x40, 0xff, 0x86, 0x44, 0x55, 0x28, 0x4d, 0x67, 0xd3, 0xb1,
	0xb9, 0x87, 0x1a, 0x50, 0xbd, 0x98, 0x9f, 0x4c, 0x47, 0x27, 0x78, 0x64, 0x1a, 0x89, 0x76, 0x36,
	0x9e, 0x7d, 0x9c, 0x4d, 0xa6, 0x73, 0xb3, 0x60, 0xdd, 0x18, 0xb0, 0x9f, 0xba, 0x0e, 0x19, 0x0d,
	0x38, 0x3a, 0x82, 0x1a, 0xa7, 0x3e, 0x89, 0xb9, 0xed, 0x87, 0xb2, 0xd0, 0x22, 0x4e, 0x01, 0x34,
	0x80, 0xea, 0x8a, 0x39, 0xb6, 0x4c, 0x55, 0xf5, 0xf8, 0xa0, 0xaf, 0x97, 0xf7, 0x8c, 0xb0, 0x0f,
	0xfa, 0x09, 0x6f, 0x49, 0xe8, 0x15, 0x94, 0xc4, 0x30, 0x63, 0x51, 0x57, 0xb2, 0x02, 0x0f, 0xf3,
	0x2d, 0xdb, 0x46, 0x4d, 0xb6, 0x20, 0x56, 0xb3, 0x97, 0xf4, 0xce, 0x6b, 0xa8, 0x6d, 0xa1, 0x1d,
	0x73, 0x6e, 0x65, 0xe7, 0x5c, 0xcb, 0x0c, 0xcf, 0xfa, 0x6e, 0xc0, 0xe1, 0x2d, 0xe7, 0x5f, 0xc4,
	0x05, 0x0a, 0xc8, 0x16, 0xb9, 0xc8, 0xdd, 0x96, 0xa0, 0xf4, 0x56, 0x1f, 0x1e, 0xde, 0x91, 0x10,
	0x4e, 0x99, 0xe8, 0x19, 0xe8, 0xdb, 0xd7, 0x15, 0xb7, 0xf3, 0x36, 0xe9, 0x95, 0x62, 0xcd, 0x3b,
	0x6d, 0xfc, 0xfa, 0xf3, 0xc0, 0xb8, 0x11, 0xdf, 0x6f, 0xf1, 0x2d, 0x2a, 0xf2, 0xac, 0x5f, 0xfc,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x05, 0xf7, 0x62, 0x19, 0x78, 0x04, 0x00, 0x00,
}
